[project]
# FIXME: change this
name = "deep-learning-intro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
  "jupytext>=1.18.1",
  "myst-nb>=1.3.0",
  "sphinx<9",
  # "sphinx-evita>=0.1.0b1",
  "sphinx-evita @ https://github.com/ENCCS/sphinx-evita/archive/refs/tags/v0.1.0b1.zip",
  # "sphinx-lesson>=0.8.19",
  # To avoid sphinx<8 restriction from sphinx-lesson and self-imposed sphinx>8.2 something restriction from sphinx-evita
  "sphinx-lesson @ https://github.com/coderefinery/sphinx-lesson/archive/96ae33057d19750b39e649ecf2431b23ac9421a4.zip",
  "sphinxcontrib-bibtex>=2.6.5",
  "sphinxcontrib-mermaid>=2.0.0",
]

[dependency-groups]
dev = [
  { include-group = "notebook" },
  "jupyterlab>=4.4.6",
  "jupyterlab-myst>=2.4.2",
]
# All dependencies used within Jupyter Notebooks
notebook = [
  "jupyter",
  "seaborn",
  "scikit-learn",
  "pandas",
  # "tensorflow",
  "pydot",
  "keras",
  "seaborn",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = false
